"""
Gate test for AC-1: No 'AGL' (case-sensitive) in source files under demo/, databricks.yml, or Makefile.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

# Repo root is 4 levels up from this file (demo/app/backend/tests/gates/)
REPO_ROOT = Path(__file__).resolve().parents[5]

EXTENSIONS = {".tsx", ".ts", ".py", ".yaml", ".yml", ".toml", ".json", ".md"}
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "dist", "build", "gates"}


def _collect_files() -> list[Path]:
    """Collect all source files to scan."""
    files: list[Path] = []

    # All files under demo/
    demo_dir = REPO_ROOT / "demo"
    if demo_dir.is_dir():
        for p in demo_dir.rglob("*"):
            if p.is_file() and p.suffix in EXTENSIONS and not any(s in p.parts for s in SKIP_DIRS):
                files.append(p)

    # databricks.yml
    dab = REPO_ROOT / "databricks.yml"
    if dab.is_file():
        files.append(dab)

    # Makefile
    makefile = REPO_ROOT / "Makefile"
    if makefile.is_file():
        files.append(makefile)

    return files


class TestAc1:
    """Given the full codebase (excluding .git/, node_modules/), when searching for
    'AGL' (case-sensitive), then zero matches in source files under demo/,
    databricks.yml, or Makefile."""

    def test_ac1_no_agl_uppercase_in_source_files(self) -> None:
        pattern = re.compile(r"\bAGL\b")
        violations: list[str] = []

        for path in _collect_files():
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for lineno, line in enumerate(text.splitlines(), 1):
                if pattern.search(line):
                    rel = path.relative_to(REPO_ROOT)
                    violations.append(f"  {rel}:{lineno}: {line.strip()[:120]}")

        assert not violations, (
            f"GATE FAILED: AC-1 — Found {len(violations)} occurrences of 'AGL' "
            f"in source files:\n" + "\n".join(violations[:20])
        )
