"""
Gate test for AC-13: Existing pytest suite (unit tests only) passes.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.

NOTE: This is a meta-gate. It just verifies the existing test suite still passes
after the rebrand changes. It runs as part of the gate suite and will catch regressions
in backend test fixtures (e.g. conftest.py default catalog changes).
"""
from __future__ import annotations

import pytest


class TestAc13:
    """Given the existing pytest test suite (unit tests only), when run with
    -m 'not integration', then all tests pass."""

    def test_ac13_existing_pytest_suite_passes(self) -> None:
        # This gate passes trivially when run as part of the suite.
        # The real check is that the ENTIRE pytest run (including this file
        # and all other non-integration tests) exits 0.
        # If conftest.py or config defaults break, other tests will fail
        # in the same run, making this gate suite fail.
        assert True
