"""
Gate test for AC-11: demo/app/frontend/src/default/ignition-logo.png exists and is a valid PNG.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
"""
from __future__ import annotations

from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[5]


class TestAc11:
    """Given the file demo/app/frontend/src/default/ignition-logo.png,
    then it exists and is a valid PNG."""

    def test_ac11_ignition_logo_exists(self) -> None:
        logo_path = REPO_ROOT / "demo" / "app" / "frontend" / "src" / "default" / "ignition-logo.png"
        assert logo_path.is_file(), (
            f"GATE FAILED: AC-11 — Ignition logo not found at {logo_path}"
        )

        # Validate PNG magic bytes
        data = logo_path.read_bytes()
        assert len(data) > 8, (
            f"GATE FAILED: AC-11 — Logo file is too small ({len(data)} bytes)"
        )
        png_magic = b"\x89PNG\r\n\x1a\n"
        assert data[:8] == png_magic, (
            f"GATE FAILED: AC-11 — File is not a valid PNG (magic bytes: {data[:8]!r})"
        )
