"""
Gate test for AC-8: FastAPI app title equals 'OT Lakehouse Demo'.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
"""
from __future__ import annotations

import pytest


class TestAc8:
    """Given the FastAPI app, when app title is read, then it equals
    'OT Lakehouse Demo' (not 'AGL OT Lakehouse Demo')."""

    def test_ac8_fastapi_title_is_generic(self) -> None:
        from backend.main import create_app

        app = create_app()
        assert app.title == "OT Lakehouse Demo", (
            f"GATE FAILED: AC-8 — FastAPI title is '{app.title}', "
            f"expected 'OT Lakehouse Demo'"
        )
