"""
Gate test for AC-9: databricks.yml bundle.name equals 'zerobus-ignition-demo'
and no variable default contains 'agl'.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

try:
    import yaml
except ImportError:
    yaml = None

REPO_ROOT = Path(__file__).resolve().parents[5]


class TestAc9:
    """Given databricks.yml, when parsed, then bundle.name equals
    'zerobus-ignition-demo' and no variable default contains 'agl'."""

    def test_ac9_databricks_yml_no_agl(self) -> None:
        dab_path = REPO_ROOT / "databricks.yml"
        assert dab_path.is_file(), f"databricks.yml not found at {dab_path}"

        text = dab_path.read_text(encoding="utf-8")

        # Check bundle name via regex (avoids yaml dependency)
        name_match = re.search(r"^\s*name:\s*(.+)$", text, re.MULTILINE)
        assert name_match, "GATE FAILED: AC-9 — No 'name:' found in databricks.yml"

        bundle_name = name_match.group(1).strip().strip('"').strip("'")
        assert bundle_name == "zerobus-ignition-demo", (
            f"GATE FAILED: AC-9 — bundle.name is '{bundle_name}', "
            f"expected 'zerobus-ignition-demo'"
        )

        # Check no 'agl' in variable defaults
        agl_pattern = re.compile(r"agl", re.IGNORECASE)
        violations: list[str] = []
        for lineno, line in enumerate(text.splitlines(), 1):
            if agl_pattern.search(line):
                violations.append(f"  databricks.yml:{lineno}: {line.strip()[:120]}")

        assert not violations, (
            f"GATE FAILED: AC-9 — Found {len(violations)} 'agl' references "
            f"in databricks.yml:\n" + "\n".join(violations)
        )
