"""
Gate test for AC-10: demo/app/frontend/src/agl/ directory does not exist.
Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
"""
from __future__ import annotations

from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[5]


class TestAc10:
    """Given the demo/app/frontend/src/agl/ directory, then it does not exist."""

    def test_ac10_agl_directory_removed(self) -> None:
        agl_dir = REPO_ROOT / "demo" / "app" / "frontend" / "src" / "agl"
        assert not agl_dir.exists(), (
            f"GATE FAILED: AC-10 — AGL directory still exists at {agl_dir}. "
            f"Contents: {list(agl_dir.iterdir()) if agl_dir.is_dir() else 'N/A'}"
        )
