/**
 * Gate test for AC-15: DataGeneration page uses generic provider names.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import DataGeneration from '../../pages/DataGeneration';

describe('AC-15: DataGeneration page uses generic provider names', () => {
  it('does not contain "agl_" prefix in any provider name', () => {
    const { container } = render(
      <MemoryRouter>
        <DataGeneration />
      </MemoryRouter>,
    );

    const pageText = container.textContent ?? '';
    expect(pageText).not.toMatch(/agl_/i);
  });
});
