/**
 * Gate test for AC-5: Landing page uses generic site names.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import Landing from '../../pages/Landing';

const AGL_SITE_NAMES = ['Tomago', 'Liddell', 'Broken Hill', 'Callide', 'Gladstone'];

describe('AC-5: Landing page uses generic site names', () => {
  it('does not contain any AGL-specific Australian site names', () => {
    const { container } = render(
      <MemoryRouter>
        <Landing />
      </MemoryRouter>,
    );

    const pageText = container.textContent ?? '';

    for (const site of AGL_SITE_NAMES) {
      expect(pageText).not.toContain(site);
    }
  });
});
