/**
 * Gate test for AC-4: Landing page hero has no AGL references.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import Landing from '../../pages/Landing';

describe('AC-4: Landing page hero has no AGL references', () => {
  it('shows Inductive Automation logo, not AGL logo', () => {
    render(
      <MemoryRouter>
        <Landing />
      </MemoryRouter>,
    );

    const images = screen.getAllByRole('img');

    // No AGL logo images
    const aglImages = images.filter(
      (img) =>
        img.getAttribute('alt')?.toLowerCase().includes('agl') ||
        img.getAttribute('src')?.toLowerCase().includes('agl'),
    );
    expect(aglImages).toHaveLength(0);
  });

  it('does not contain text "AGL" anywhere on the page', () => {
    const { container } = render(
      <MemoryRouter>
        <Landing />
      </MemoryRouter>,
    );

    const pageText = container.textContent ?? '';
    expect(pageText).not.toMatch(/\bAGL\b/);
  });
});
