/**
 * Gate test for AC-6: Scenario labels are generic.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import ScenarioSwitcher from '../../components/ScenarioSwitcher';

describe('AC-6: Scenario labels are generic', () => {
  it('scenario buttons do not contain Hexham or Liddell', () => {
    render(
      <ScenarioSwitcher activeScenario="mixed" onScenarioChange={vi.fn()} />,
    );

    const buttons = screen.getAllByRole('button');
    for (const btn of buttons) {
      const text = btn.textContent ?? '';
      expect(text).not.toContain('Hexham');
      expect(text).not.toContain('Liddell');
    }
  });
});
