/**
 * Gate test for AC-14: Analytics page uses generic currency and market terms.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import Analytics from '../../pages/Analytics';

describe('AC-14: Analytics page uses generic currency and market terms', () => {
  it('does not contain "NEM" in page text', () => {
    const { container } = render(
      <MemoryRouter>
        <Analytics />
      </MemoryRouter>,
    );

    const pageText = container.textContent ?? '';
    expect(pageText).not.toMatch(/\bNEM\b/);
  });

  it('does not contain "AUD" in page text', () => {
    const { container } = render(
      <MemoryRouter>
        <Analytics />
      </MemoryRouter>,
    );

    const pageText = container.textContent ?? '';
    expect(pageText).not.toMatch(/\bAUD\b/);
  });
});
