/**
 * Gate test for AC-3: Sidebar shows Ignition logo and generic heading.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import Sidebar from '../../components/Sidebar';

describe('AC-3: Sidebar shows Ignition logo and generic heading', () => {
  it('renders an Inductive Automation / Ignition logo, not AGL', () => {
    render(
      <MemoryRouter>
        <Sidebar />
      </MemoryRouter>,
    );

    // Should NOT have an AGL logo
    const images = screen.getAllByRole('img');
    const aglImages = images.filter(
      (img) =>
        img.getAttribute('alt')?.toLowerCase().includes('agl') ||
        img.getAttribute('src')?.toLowerCase().includes('agl'),
    );
    expect(aglImages).toHaveLength(0);

    // Should have an Ignition-related logo
    const ignitionImages = images.filter(
      (img) =>
        img.getAttribute('alt')?.toLowerCase().includes('ignition') ||
        img.getAttribute('alt')?.toLowerCase().includes('inductive') ||
        img.getAttribute('src')?.toLowerCase().includes('ignition'),
    );
    expect(ignitionImages.length).toBeGreaterThan(0);
  });

  it('heading says "OT Lakehouse" not "AGL OT Lakehouse"', () => {
    render(
      <MemoryRouter>
        <Sidebar />
      </MemoryRouter>,
    );

    // The sidebar heading should contain "OT" and "Lakehouse" but NOT "AGL"
    const heading = screen.getByRole('heading', { level: 1 });
    expect(heading.textContent).toContain('OT');
    expect(heading.textContent).toContain('Lakehouse');
    expect(heading.textContent).not.toContain('AGL');
  });
});
