/**
 * Gate test for AC-7: Tailwind config uses ignition colour not agl.
 * Auto-generated by relentless-gates. DO NOT EDIT — regenerate from PRD.
 */
import { describe, it, expect } from 'vitest';
import tailwindConfig from '../../../tailwind.config';

describe('AC-7: Tailwind config uses ignition colour not agl', () => {
  it('does not have an "agl" colour key', () => {
    const colors = (tailwindConfig as any).theme?.extend?.colors ?? {};
    expect(colors).not.toHaveProperty('agl');
  });

  it('has an "ignition" colour key with a blue value', () => {
    const colors = (tailwindConfig as any).theme?.extend?.colors ?? {};
    expect(colors).toHaveProperty('ignition');
    expect(colors.ignition).toHaveProperty('blue');
    expect(typeof colors.ignition.blue).toBe('string');
    expect(colors.ignition.blue).toMatch(/^#[0-9A-Fa-f]{6}$/);
  });
});
