/**
 * Gate test for AC-1: 1h button on Asset Detail still works.
 * Auto-generated by relentless-gates.
 */
import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';

describe('AC-1: Extended Time Range — 1h preset preserved', () => {
  it('renders time range selector with 1h option on Asset Detail page', async () => {
    // Dynamic import to avoid build errors if page doesn't exist yet
    let AssetDetail: any;
    try {
      const mod = await import('../../pages/AssetDetail');
      AssetDetail = mod.default;
    } catch {
      expect.fail('GATE NOT PASSED: AC-1 — AssetDetail page cannot be imported');
      return;
    }

    render(
      <MemoryRouter initialEntries={['/assets/bess01']}>
        <Routes>
          <Route path="/assets/:assetId" element={<AssetDetail />} />
        </Routes>
      </MemoryRouter>,
    );

    // Should have a 1h button/option
    const hourButton = screen.queryByRole('button', { name: /1h/i })
      ?? screen.queryByText(/1h/i);
    expect(hourButton).toBeTruthy();
  });
});
